version: '3.9'

services:

    r3con-ui:
        container_name: sample_dev
        build:
            context: .
            dockerfile: Dockerfile
        volumes: 
            - '.:/usr/src/app'
            - '/usr/src/app/node_modules'
        ports:
            - 3001:3000
        environment: 
            - CHOKIDAR_USEPOLLING=true